### ISSUE TITLE
Unlock doesnt work with master passwords that have spaces

### ISSUE THREAD

**Issue by bmatticus** [0neTX/Bitwarden_Export#14]
If you use spaces in your master password this currently does not work. Simple fix, though, as the $bw_password just needs to be encapsulated in quotes to fix.

**Comment by bmatticus** [comment]
Created PR #15 for potential fix

**Comment by 0neTX** [comment]
Thanks for your PR! Pending to integration test, I'll accept the PR  after the test it in a few hours.
