### ISSUE TITLE
ARM Arch Docker

### ISSUE THREAD

**Issue by johannmx** [0neTX/Bitwarden_Export#16]
Can't running the docker image on ARM Arch like RaspberryPi or Oracle ARM VMs

**Comment by 0neTX** [comment]
Our image is based on [Bitwarden Cli application](https://bitwarden.com/es-la/help/cli/). Unfortunately Bitwarden don't provide this application for ARM architecture. They have a related open issue: [ARM support for CLI](https://community.bitwarden.com/t/arm-support-for-cli/42362)

As soon as Bitwarden releases an Arm-compatible version, we will adapt the image to support ARM.
Sorry.
