### ISSUE TITLE
send notifications through discord 

### ISSUE THREAD

**Issue by sistemmsn** [0neTX/Bitwarden_Export#18]
This is more than an integration, we can send notifications through discord just like it does with telegram, I'm going to implement it right now I'm using vaultwarden

**Comment by 0neTX** [comment]
The service already supports notifications to Discord thanks to Shoutrrr, check how to generate the notification URL at the following link :
https://containrrr.dev/shoutrrr/v0.8/services/overview/

And set the NOTIFICATION_URL variable to the appropriate URL. 

Any issues answer this thread
