### ISSUE TITLE
Environment variable for retention policy

### ISSUE THREAD

**Issue by dgongut** [0neTX/Bitwarden_Export#7]
First of all, congratulations on the project, very interesting and useful.

To extend the functionality of the docker program, I would like to have the ability to set a file retention policy.
I was thinking of a KEEP_LAST_X_FILES variable or something to tell it that we want to keep the last X files.

In my case I run this backup daily and after 1 month I'll have 30 files having to delete them by hand
<img width="377" alt="image" src="https://github.com/0neTX/Bitwarden_Export/assets/48691032/6e3c99c5-e709-4797-ae5c-3beb09f56416">

Thanks

**Comment by 0neTX** [comment]
## KEEP_LAST_BACKUPS Variable

Keep the maximum number of exports defined. A maximum of X exports will be retained, the oldest exports will be deleted.

```yaml
environment:
  - KEEP_LAST_BACKUPS=5
```

Each export is saved in the output folder with the template `<DateTime>-bw-export`.
When the variable `KEEP_LAST_BACKUPS` is set, the container will sort the folders and delete the oldest ones while keeping the number of folders indicated by the variable.

![imagen](https://github.com/0neTX/Bitwarden_Export/assets/56652076/3eaa852f-4d96-4d25-9669-f328d744e8db)


These changes have been published with the beta tag: `0netx/bw-export:beta`

[0netx/bw-export:beta](https://hub.docker.com/layers/0netx/bw-export/beta/images/sha256-6df9ca9fb364343831287a88a5f1cd6459d8f43c3e26d1a42f05cdf903c61386?context=explore)

Please test this version and I look forward to your feedback.

**Comment by 0neTX** [comment]
Released at [v1.5](https://github.com/0neTX/Bitwarden_Export/releases/tag/v1.5)

Thanks!!
